name: Test libs

on:
  workflow_call:
    inputs:
      lib-name:
        required: true
        type: string
      configuration:
        required: true
        type: string

runs:
  using: "composite"
  steps:
    - name: Unit tests
      id: unittests
      continue-on-error: true
      shell: bash
      run: mono ~/.nuget/packages/xunit.runner.console/*/tools/net472/xunit.console.exe ./${{ inputs.lib-name }}.UnitTests/bin/${{ inputs.configuration }}/net461/${{ inputs.lib-name }}.UnitTests.dll -junit test-results.xml

    - name: Test Report - Unit Tests
      uses: dorny/test-reporter@v1.9.1
      if: success() || (failure() && steps.unittests.outcome == 'failure')
      with:
        name: ${{ inputs.lib-name }} Unit Tests Results
        path: "test-results.xml"
        reporter: java-junit
