name: Publish libs

on:
  workflow_call:
    inputs:
      lib-version:
        required: true
        type: string
      lib-name:
        required: true
        type: string
      spec-file:
        required: true
        type: string
      configuration:
        required: true
        type: string

runs:
  using: "composite"
  steps:
    - name: "Package ${{ inputs.lib-name }}"
      shell: bash
      run: nuget pack ${{ inputs.spec-file }} -properties Configuration=${{ inputs.configuration }} -Version ${{ inputs.lib-version }}

    - name: "Publish ${{ inputs.lib-name }}"
      shell: bash
      run: nuget push *.nupkg -ApiKey ${{ secrets.NUGET_API_KEY }} -Source https://api.nuget.org/v3/index.json -SkipDuplicate
