name: Security Scan Repo

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  security-events: write
  checks: write
  actions: read

jobs:
  security_scan:
    uses: ZeroGachis/.github/.github/workflows/security_scan_repo.yml@v4
    secrets: inherit
