name: Poetry install dependencies
description: |
  Install python dependencies dependencies with poetry.

  This action login on AWS in order to install
  Smartway's private packages from AWS CodeArtifact.

  Installed dependencies are cached.

  Prerequisites: Python & poetry must be installed, and 
  the repository must be checked-out.

inputs:
  aws_account_id:
    required: true
  install_options:
    required: false
  depends_on_private_packages:
    description: "Set to false if your project does not depends on private packages on AWS CodeArtifact"
    required: false
    type: boolean
    default: true

runs:
  using: "composite"
  steps:
    - name: Define a cache for the virtual environment based on the dependencies lock file
      uses: actions/cache@v5
      id: cache-python-deps
      with:
        path: ./.venv
        key: venv-${{ runner.os }}-${{ hashFiles('poetry.lock') }}-${{ inputs.install_options }}
    - name: Authenticate on AWS
      if: steps.cache-python-deps.outputs.cache-hit != 'true' && ${{ inputs.depends_on_private_packages == true }}
      id: aws
      uses: aws-actions/configure-aws-credentials@v5
      with:
        aws-region: eu-west-3
        role-to-assume: arn:aws:iam::${{ inputs.aws_account_id }}:role/github_oidc_readonly
        output-credentials: true
    - name: Setup private repository credentials
      run: ./scripts/setup_private_repo_credentials.sh
      shell: bash
      if: steps.cache-python-deps.outputs.cache-hit != 'true' && ${{ inputs.depends_on_private_packages == true }}
    - name: Install dependencies
      run: poetry install ${{ inputs.install_options }}
      shell: bash
      if: steps.cache-python-deps.outputs.cache-hit != 'true'
