name: 'BuildImage'

on:
  workflow_call:
    inputs:
      working-directory:
        required: false
        type: string
      dockerfile_context:
        required: true
        type: string
      regitry_url:
        required: true
        type: string
      regitry_username:
        required: false
        type: string
      regitry_password:
        required: false
        type: string
      image_name:
        required: false
        type: string
        default: ${{ github.event.repository.name }}
      image_target:
        required: false
        type: string
      build-args:
        required: false
        type: string
      tailscale_enabled:
        required: false
        type: boolean
        default: true
      vault_enabled:
        required: false
        type: boolean
        default: true
      vault_url:
        required: false
        type: string
      vault_github_actions_role:
        required: false
        type: string
      environment_name:
        required: false
        type: string
    outputs:
      image-url:
        value: ${{ jobs.build-image.outputs.image-url }}
      image-version:
        value: ${{ jobs.build-image.outputs.image-version }}


jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        id-token: write
        packages: write
    environment:
      name: ${{ inputs.environment_name }}
    env:
      VAULT_URL: ${{ inputs.VAULT_URL || vars.VAULT_URL || vars.PULLREQUEST_VAULT_URL }}
      VAULT_GITHUB_ACTIONS_ROLE: ${{ inputs.vault_github_actions_role || vars.VAULT_GITHUB_ACTIONS_ROLE }}
      AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID || vars.PULL_REQUEST_AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ vars.AWS_REGION || vars.AWS_DEFAULT_REGION }}
    outputs:
      image-url: ${{ steps.meta.outputs.tags }}
      image-version: ${{ steps.meta.outputs.version }}
    steps:
      - name: Tailscale
        if: inputs.tailscale_enabled || inputs.vault_enabled
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          version: ${{ vars.TAILSCALE_VERSION }}

      - name: Sleep for 10 seconds
        run: sleep 10s
        shell: bash

      - name: Checkout
        uses: actions/checkout@v4

      - name: Import Secrets
        if: inputs.vault_enabled
        id: secrets
        uses: hashicorp/vault-action@a727ce205a9e187cf179d30796762854cac9c231
        with:
          url: ${{ env.VAULT_URL }}
          role: ${{ env.VAULT_GITHUB_ACTIONS_ROLE }}
          method: jwt
          path: "github-actions"
          exportToken: true
          secrets: |
              secret/data/github-actions-common/github/read-repo-token USERNAME | GH_ORG_READ_REPO_USER ;
              secret/data/github-actions-common/github/read-repo-token PASSWORD | GH_ORG_READ_REPO_TOKEN ;

      - name: Configure AWS Credentials
        id: aws
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github_oidc_readonly
          output-credentials: true

      - name: Login to Github Packages
        if: contains(inputs.regitry_url,'ghcr')
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.regitry_url }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.regitry_url }}/${{ github.repository_owner	 }}/${{ inputs.image_name }}
          labels: |
            org.opencontainers.image.source=github.com/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
          flavor: |
            latest=false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: "v0.11.2"

      - name: Build
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ${{ inputs.dockerfile_context }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: ${{ inputs.image_target }}
          build-args: |
            ${{ inputs.build-args }}
            GITHUB_USER=${{ steps.secrets.outputs.GH_ORG_READ_REPO_USER }}
            GITHUB_TOKEN=${{ steps.secrets.outputs.GH_ORG_READ_REPO_TOKEN }}
            AWS_ACCESS_KEY_ID=${{ steps.aws.outputs.aws-access-key-id }}
            AWS_SECRET_ACCESS_KEY=${{ steps.aws.outputs.aws-secret-access-key }}
            AWS_SESSION_TOKEN=${{ steps.aws.outputs.aws-session-token }}
            CODEARTIFACT_DOMAIN=smartway
            CODEARTIFACT_DOMAINOWNER=007065811408
