name: "Build-Push-Image-To-DockerHub"

on:
  workflow_call:
    inputs:
      dockerfile_context:
        required: true
        type: string
      dockerhub_repository_name:
        required: true
        type: string
      tag:
        required: false
        type: string

jobs:
  push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKERHUB_USERNAME }}/${{ inputs.dockerhub_repository_name }}
          tags: |
             ${{ inputs.tag != '' && format('type=semver,pattern={{version}},value={0}', inputs.tag) || format('type=sha,format=short') }}
          labels: |
            org.opencontainers.image.source=github.com/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
          flavor: |
            latest=false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ${{ inputs.dockerfile_context }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
