name: 'Delete-Docker-Image'

on:
  workflow_call:
    inputs:
      image_version:
        required: true
        type: string
      image_name:
        required: false
        type: string
        default: ${{ github.event.repository.name }}
      vault_url:
        required: false
        type: string
      vault_github_actions_role:
        required: false
        type: string
      environment_name:
        required: false
        type: string

jobs:
  delete:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        id-token: write
        packages: write
    environment:
      name: ${{ inputs.environment_name }}
    env:
      VAULT_URL: ${{ inputs.VAULT_URL || vars.VAULT_URL || vars.PULLREQUEST_VAULT_URL }}
      VAULT_GITHUB_ACTIONS_ROLE: ${{ inputs.vault_github_actions_role || vars.VAULT_GITHUB_ACTIONS_ROLE }}
    steps:
      # We keep this action as it is configure in lot of repo
      # the legacy version did not work this is why we removed it
      # TODO: find a way to delete images from github registry
      - name: None
        run: echo "Enjoy"
