name: "Dockerfile linter"

on:
  workflow_call:
    inputs:
      dockerfile_path:
        required: true
        type: string
      image_name:
        required: true
        type: string

jobs:
  lint-dockerfile:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: read
      actions: read
      checks: write
      issues: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ inputs.dockerfile_path }}
          output-file: test-report.json
          format: json
