name: Helm Testing

on:
  workflow_call:
    inputs:
      charts_root_dir:
        description: "Chart path to test"
        type: string
        required: true
      target_branch:
        description: "Target branch as ref"
        type: string
        required: false

jobs:
  helm-test:
    runs-on: ubuntu-latest
    env:
      TARGET_BRANCH: ${{ inputs.target_branch }} || ${{ github.event.repository.default_branch }}
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Helm Install
        uses: azure/setup-helm@v4

      - uses: actions/setup-python@v6
        with:
          python-version: "3.x"
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: Run chart-testing (lint)
        run: ct lint --chart-dirs ${{ inputs.charts_root_dir }} --target-branch ${{ inputs.target_branch }} --check-version-increment=false
