name: 'Push-Pypi'

on:
  workflow_call:
    inputs:
      image_url:
        required: true
        type: string
      workdir:
        required: true
        type: string
      checkout_enabled:
        required: false
        type: boolean
        default: false

jobs:
  push-pypi:
    runs-on: ubuntu-latest
    container: 
      image: ${{ inputs.image_url }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Checkout
        if: ${{ inputs.checkout_enabled }}
        uses: actions/checkout@v3

      - name: run-command
        working-directory: ${{ inputs.workdir }}
        run: poetry publish --build -u ${{ secrets.PYPI_USER }} -p ${{ secrets.PYPI_PWD }} 