name: 'Run-Docker-Command'

on:
  workflow_call:
    inputs:
      image_url:
        required: true
        type: string
      workdir:
        required: true
        type: string
      run_command:
        required: true
        type: string
      enable_test_report:
        required: false
        type: boolean
        default: false
      test_report_name:
        required: false
        type: string
      test_report_path:
        required: false
        type: string
      test_report_format:
        required: false
        type: string
      env_django_settings_module:
        required: false
        type: string
      aws_credentials_enabled: 
        required: false
        type: boolean
        default: false
      checkout_enabled:
        required: false
        type: boolean
        default: true
      vault_url: 
        required: false
        type: string
      vault_github_actions_role:
        required: true 
        type: string
      environment_name:
        required: false
        type: string

jobs:
  run-docker:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        id-token: write
        packages: read
        actions: write
        checks: write
    environment:
      name: ${{ inputs.environment_name }}
    container: 
      image: ${{ inputs.image_url }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
      env: 
        DJANGO_SETTINGS_MODULE: ${{ inputs.env_django_settings_module }}
        GIT_DISCOVERY_ACROSS_FILESYSTEM: 1
    services: 
      postgres:
        image: postgres:12
        env:
          POSTGRES_PASSWORD: postgres
        ports: 
        - 5432:5432

    steps:
      - name: Tailscale
        if: ${{ inputs.aws_credentials_enabled }}
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTH_KEY }}
          version: ${{ vars.TAILSCALE_VERSION }}

      - name: Import Secrets
        if: ${{ inputs.aws_credentials_enabled }}
        id: secrets
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ inputs.VAULT_URL || vars.VAULT_URL }}
          role: ${{ inputs.VAULT_GITHUB_ACTIONS_ROLE }}
          method: jwt
          path: "github-actions"
          secrets: |
              secret/data/github-actions-common/aws accessKey | AWS_ACCESS_KEY_ID ;
              secret/data/github-actions-common/aws secretKey | AWS_SECRET_ACCESS_KEY ;

      - name: Checkout
        if: ${{ inputs.checkout_enabled }}
        uses: actions/checkout@v3
        
      - name: Configure AWS Credentials
        if: ${{ inputs.aws_credentials_enabled }}
        uses: aws-actions/configure-aws-credentials@v2.0.0
        with:
          aws-access-key-id: ${{ steps.secrets.outputs.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ steps.secrets.outputs.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: run-command
        working-directory: ${{ inputs.workdir }}
        env: 
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
        run: ${{ inputs.run_command }}

      - name: Test Report
        uses: dorny/test-reporter@e9fa2f582c0ebbe2e263fd18fad744d52e0b0203
        id: test-report               
        if: ${{ always() && inputs.enable_test_report == true }}
        with:
          name: '${{ inputs.test_report_name }}'         
          path: ${{ inputs.workdir }}/${{ inputs.test_report_path }}
          working-directory: ${{ inputs.workdir }}
          reporter: ${{ inputs.test_report_format }}
          max-annotations: 0
