name: 'Run-Docker-Command'

on:
  workflow_call:
    inputs:
      image_url:
        required: true
        type: string
      workdir:
        required: true
        type: string
      env_django_settings_module:
        required: false
        type: string
      run_command:
        required: true
        type: string
      aws_credentials_enabled:
        required: false
        type: boolean
        default: false
      enable_test_report:
        required: false
        type: boolean
        default: false
      test_report_name:
        required: false
        type: string
      test_report_path:
        required: false
        type: string
      test_report_format:
        required: false
        type: string
      checkout_enabled:
        required: false
        type: boolean
        default: true

jobs:
  run-docker:
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image_url }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
      env:
        DJANGO_SETTINGS_MODULE: ${{ inputs.env_django_settings_module }}
        GIT_DISCOVERY_ACROSS_FILESYSTEM: 1
    steps:
      - name: Checkout
        if: ${{ inputs.checkout_enabled }}
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        if: ${{ inputs.aws_credentials_enabled }}
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: run-command
        working-directory: ${{ inputs.workdir }}
        run: ${{ inputs.run_command }}

      - name: Test Report
        uses: dorny/test-reporter@e9fa2f582c0ebbe2e263fd18fad744d52e0b0203
        id: test-report
        if: ${{ always() && inputs.enable_test_report == true }}
        with:
          name: '${{ inputs.test_report_name }}'
          path: ${{ inputs.workdir }}/${{ inputs.test_report_path }}
          reporter: ${{ inputs.test_report_format }}
          working-directory: ${{ inputs.workdir }}
          max-annotations: 0

