name: "Run-Python"

on:
  workflow_call:
    inputs:
      python_version:
        required: false
        type: string
        default: "3.x"
      environment_name:
        required: false
        type: string
        default: ""
      vault_enabled:
        required: false
        type: boolean
        default: true
      vault_url:
        required: false
        type: string
      vault_github_actions_role:
        required: true
        type: string
      vault_secrets:
        required: true
        type: string
      tailscale_enabled:
        required: false
        type: boolean
        default: true
      run_command:
        required: true
        type: string

jobs:
  run-python:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        id-token: write
        packages: read
    environment:
      name: ${{ inputs.environment_name }}
    env:
      VAULT_URL: ${{ inputs.VAULT_URL || vars.VAULT_URL || vars.PULLREQUEST_VAULT_URL }}
      VAULT_GITHUB_ACTIONS_ROLE: ${{ inputs.vault_github_actions_role || vars.VAULT_GITHUB_ACTIONS_ROLE }}
      AWS_ACCOUNT_ID: ${{ inputs.AWS_ACCOUNT_ID || vars.AWS_ACCOUNT_ID || vars.PULL_REQUEST_AWS_ACCOUNT_ID }}

    steps:
      - name: Tailscale
        if: inputs.tailscale_enabled || inputs.vault_enabled
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          version: ${{ vars.TAILSCALE_VERSION }}

      - name: Sleep for 10 seconds
        run: sleep 10s
        shell: bash

      - name: Import Secrets
        if: inputs.vault_enabled
        id: secrets
        uses: hashicorp/vault-action@9f522b85981b491eab9a52c144d15aedbd0bf371
        with:
          url: ${{ env.VAULT_URL }}
          role: ${{ env.VAULT_GITHUB_ACTIONS_ROLE }}
          method: jwt
          path: "github-actions"
          exportToken: true
          secrets: |
            ${{ inputs.vault_secrets }}

      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}

      - name: run-command
        run: ${{ inputs.run_command }}
