name: "Run-AWS"

on:
  workflow_call:
    inputs:
      aws_region:
        required: false
        type: string
      aws_account_id:
        required: false
        type: string
      aws_github_role_name:
        required: false
        type: string
        default: "github_oidc_readonly"
      environment_name:
        required: false
        type: string
        default: ""
      tailscale_enabled:
        required: false
        type: boolean
        default: true
      vault_enabled:
        required: false
        type: boolean
        default: true
      vault_url:
        required: false
        type: string
      vault_github_actions_role:
        required: false
        type: string
      vault_secrets:
        required: false
        type: string
      run_command:
        required: true
        type: string

jobs:
  run-aws:
    permissions:
        contents: read
        id-token: write
        packages: read
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment_name }}
    env:
      VAULT_URL: ${{ inputs.VAULT_URL || vars.VAULT_URL || vars.PULLREQUEST_VAULT_URL }}
      VAULT_GITHUB_ACTIONS_ROLE: ${{ inputs.vault_github_actions_role || vars.VAULT_GITHUB_ACTIONS_ROLE }}
      AWS_ACCOUNT_ID: ${{ inputs.AWS_ACCOUNT_ID || vars.AWS_ACCOUNT_ID || vars.PULL_REQUEST_AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ inputs.AWS_REGION || vars.AWS_REGION || vars.AWS_DEFAULT_REGION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Tailscale
        if: inputs.tailscale_enabled || inputs.vault_enabled
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          version: ${{ vars.TAILSCALE_VERSION }}

      - name: Import Secrets
        uses: Wandalen/wretry.action@v3
        if: inputs.vault_enabled
        id: secrets
        with:
          action: hashicorp/vault-action@v3
          attempt_limit: 5
          attempt_delay: 150
          with: |
            url: ${{ env.VAULT_URL }}
            role: ${{ env.VAULT_GITHUB_ACTIONS_ROLE }}
            method: jwt
            path: "github-actions"
            exportToken: true
            secrets: |
              ${{ inputs.vault_secrets }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ inputs.aws_github_role_name }}

      - name: run-command
        run: ${{ inputs.run_command }}
