name: Scan a docker image for security vulnerabilities and push the result to Github Code Scanning

on:
  workflow_call:
    inputs:
      repository:
        description: Name of the registry's repository where the docker image will be pulled from
        required: true
        type: string
      release-tag:
        description: Release tag of the docker image to pull
        required: false
        type: string
        default: latest
      severity:
        description: "Comma-separated list of severities to report"
        required: false
        type: string
        default: "CRITICAL,HIGH"
      exit-code:
        description: "Exit code when vulnerabilities are found (0: do not fail, 1: fail)"
        required: false
        type: string
        default: "0"
      aws_account_id:
        description: AWS account ID to use for ECR authentication
        required: false
        type: string
      aws_region:
        description: AWS region to use for ECR authentication
        required: false
        type: string
      use-org-docker-image-ignore-rules:
        description: Use org-level vulnerability ignore rules when scanning an image
        required: false
        type: boolean
        default: true
      ignore-vulnerabilities-from-base-image-layers:
        description: Ignore vulnerabilities from the base image layers
        required: false
        type: boolean
        default: true

jobs:
  security-scan-image:
    runs-on: ubuntu-latest
    permissions:
      actions: read # required for a private repository by github/codeql-action/upload-sarif to get the Action run status
      contents: read # required to checkout the repository
      id-token: write # required by aws-actions/configure-aws-credentials
      packages: read # required to pull the image from ghcr.io
      pull-requests: write
      security-events: write # required for github/codeql-action/upload-sarif to upload SARIF results
    env:
      AWS_ACCOUNT_ID: ${{ inputs.aws_account_id || vars.AWS_ACCOUNT_ID || vars.PULL_REQUEST_AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ inputs.aws_region || vars.AWS_REGION || vars.AWS_DEFAULT_REGION }}
      TOOLS_AWS_ACCOUNT_ID: ${{ vars.TOOLS_AWS_ACCOUNT_ID }}
      TOOLS_AWS_REGION: ${{ vars.TOOLS_AWS_REGION }}
    steps:
      - name: Set image's ECR url
        id: image-ecr-url
        run: echo "url=${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com" >> $GITHUB_OUTPUT

      - name: Set base image's ECR url
        id: base-image-ecr-url
        run: echo "url=${{ env.TOOLS_AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.TOOLS_AWS_REGION }}.amazonaws.com" >> $GITHUB_OUTPUT

      - name: Set docker image ref
        id: image-ref
        run: echo "value=${{ steps.image-ecr-url.outputs.url }}/${{ inputs.repository }}:${{ inputs.release-tag }}" >> $GITHUB_OUTPUT

      - name: Get trivy ignore rules
        id: get-trivy-ignore-rules
        uses: ZeroGachis/.github/.github/actions/get-trivy-ignore-rules@main
        with:
          smartway_github_bot_id: ${{ secrets.SW_BOT_APP_ID }}
          smartway_github_bot_private_key: ${{ secrets.SW_BOT_APP_PRIVATE_KEY }}
          use-org-docker-image-ignore-rules: ${{ inputs.use-org-docker-image-ignore-rules }}

      - name: Output .trivyignore file
        run: |
          # Output .trivyignore file
          cat << 'EOF' > .trivyignore-final
          ${{ steps.get-trivy-ignore-rules.outputs.trivyignore }}
          EOF

      - name: Configure AWS Credentials for <env> account
        id: aws
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github_oidc_readonly
          output-credentials: true

      - name: Login to <env>'s ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: ${{ env.AWS_ACCOUNT_ID }}

      - name: Pull docker image
        run: docker pull ${{ steps.image-ref.outputs.value }}

      - name: Extract base image name
        if: inputs.ignore-vulnerabilities-from-base-image-layers
        id: base-image-name
        run: |
          echo "value=$(docker inspect --format '{{ index .Config.Labels "org.opencontainers.image.base.name" }}' ${{ steps.image-ref.outputs.value }})" >> $GITHUB_OUTPUT

      - name: Configure AWS Credentials for Tools account
        if: inputs.ignore-vulnerabilities-from-base-image-layers && steps.base-image-name.outputs.value != ''
        id: aws
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: ${{ env.TOOLS_AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ env.TOOLS_AWS_ACCOUNT_ID }}:role/github_oidc_readonly
          output-credentials: true

      - name: Login to Tools' ECR
        if: inputs.ignore-vulnerabilities-from-base-image-layers && steps.base-image-name.outputs.value != ''
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: ${{ env.TOOLS_AWS_ACCOUNT_ID }}

      - name: Pull base image from Tools' ECR
        if: inputs.ignore-vulnerabilities-from-base-image-layers && steps.base-image-name.outputs.value != ''
        run: docker pull ${{ steps.base-image-ecr-url.outputs.url }}/${{ steps.base-image-name.outputs.value }}

      - name: Create empty ignore policy
        shell: node {0}
        run: | # JS
          import { writeFileSync } from 'fs';
          writeFileSync('ignore_policy.rego', 'package trivy\n');

      - name: Add base image layers in ignore policy
        if: inputs.ignore-vulnerabilities-from-base-image-layers && steps.base-image-name.outputs.value != ''
        shell: node {0}
        env:
          BASE_IMAGE: ${{ steps.base-image-ecr-url.outputs.url }}/${{ steps.base-image-name.outputs.value }}
        run: | # JS
          // Create base image layers ignore rules
          // Cf: https://trivy.dev/docs/latest/configuration/filtering/#by-rego
          import { execSync } from 'child_process';
          import { writeFileSync } from 'fs';

          const baseImage = process.env.BASE_IMAGE;
          const output = execSync(`docker inspect ${baseImage} --format='{{json .RootFS.Layers}}'`).toString().trim();
          const layers = JSON.parse(output);

          const baseLayers = layers.map(l => `    "${l}",`).join('\n');

          // we don't use a simple string interpolation here because it breaks the visual indentation
          // with the overall workflow.
          const regoContent = [
            'package trivy',
            '',
            'base_layers := {',
            baseLayers,
            '}',
            '',
            'default ignore = false',
            '',
            'ignore {',
            '    base_layers[input.Layer.DiffID]',
            '}',
            '',
          ].join('\n');

          writeFileSync('ignore_policy.rego', regoContent);
          console.log(`Created ignore_policy.rego with ${layers.length} base image layers`);

      - name: Analyze docker image
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          version: v0.70.0
          scan-type: "image"
          image-ref: ${{ steps.image-ref.outputs.value }}
          format: "sarif"
          output: "trivy-results-image.sarif"
          severity: ${{ inputs.severity }}
          exit-code: ${{ inputs.exit-code }}
          trivyignores: ".trivyignore-final"
          ignore-unfixed: true
          ignore-policy: ignore_policy.rego

      # Rename the tool driver to Trivy-image-and-fs so it appears in GitHub Security tab
      # in the same panel for trivy image and trivy fs reports
      - name: Edit docker image analysis
        run: |
          jq ".runs[0].tool.driver.name = \"Trivy-image-and-fs\"" ./trivy-results-image.sarif > ./trivy-results-image-edited.sarif

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v3
        if: github.event.pull_request
        with:
          message: |
            :shield: The security scan result : [Image](https://github.com/${{ github.repository }}/security/code-scanning?query=is%3Aopen+ref%3A${{ github.ref }}+tool%3ATrivy-image-and-fs)
          comment-tag: "The security scan result of the image"

      - name: Upload docker analysis to Github Code Scanning
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: "trivy-results-image-edited.sarif"
