name: "Upload-Dbt-Manifest"

on:
  workflow_call:
    inputs:
      aws_credentials_enabled:
        required: false
        type: boolean
        default: false
      snowflake_dbt_schema:
        required: false
        type: string
        default: dbt_ci
      project_dir:
        required: false
        type: string
        default: smartway
      aws_github_role_name:
        required: false
        type: string
        default: "github_oidc"
      aws_account_id:
        required: false
        type: string
      environment_name:
        required: false
        type: string
      python_version:
        required: false
        type: string
        default: "3.12"

jobs:
  update-dbt-manifest:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment_name }}
    env:
      AWS_ACCOUNT_ID: ${{ inputs.AWS_ACCOUNT_ID || vars.AWS_ACCOUNT_ID || vars.PULL_REQUEST_AWS_ACCOUNT_ID }}
      BACKUP_BUCKET_NAME: ${{ vars.BACKUP_BUCKET_NAME }}
      TECH_PORTAL_DATA_BUCKET_NAME: ${{ vars.TECH_PORTAL_DATA_BUCKET_NAME }}
      DBT_TYPE: snowflake
      DBT_PROFILES_DIR: ${{ github.workspace }}/${{ inputs.project_dir }}
      SNOWFLAKE_DBT_SCHEMA: ${{ inputs.snowflake_dbt_schema }}
      VAULT_URL: ${{ inputs.VAULT_URL || vars.VAULT_URL || vars.PULLREQUEST_VAULT_URL }}
      VAULT_GITHUB_ACTIONS_ROLE: ${{ inputs.vault_github_actions_role || vars.VAULT_GITHUB_ACTIONS_ROLE }}
    permissions:
      contents: read
      id-token: write
      issues: read
      pull-requests: write
      packages: read
    steps:

      - name: Checkout
        uses: actions/checkout@v5

      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          version: ${{ vars.TAILSCALE_VERSION }}

      - name: Check DNS Resolution for Vault
        run: |
          extract_domain() {
            echo "$1" | awk -F[/:] '{print $4}'
          }
          VAULT_DOMAIN=$(extract_domain "${{ vars.VAULT_URL }}")
          for i in {1..100}; do
            if nslookup $VAULT_DOMAIN; then
              echo "DNS resolution successful"
              break
            else
              echo "DNS resolution failed, retrying in 10 seconds..."
              sleep 15
            fi
          done
          # Exit with error if DNS resolution fails after retries
          if ! nslookup $VAULT_DOMAIN; then
            echo "DNS resolution failed after multiple attempts"
            exit 1
          fi
        shell: bash

      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@v3
        with:
          url: ${{ vars.VAULT_URL }}
          role: ${{ vars.VAULT_GITHUB_ACTIONS_ROLE }}
          method: jwt
          path: "github-actions"
          exportToken: true
          secrets: |
              secret/data/snowflake/ecs SNOWFLAKE_ACCOUNT | SNOWFLAKE_ACCOUNT ;
              secret/data/dbt/github-actions SNOWFLAKE_DBNAME | SNOWFLAKE_DBNAME ;
              secret/data/dbt/github-actions SNOWFLAKE_DBT_PRIVATE_KEY | SNOWFLAKE_DBT_PRIVATE_KEY ;
              secret/data/dbt/github-actions SNOWFLAKE_DBT_PRIVATE_KEY_PASSWORD | SNOWFLAKE_DBT_PRIVATE_KEY_PASSWORD ;
              secret/data/dbt/github-actions SNOWFLAKE_DBT_ROLE | SNOWFLAKE_DBT_ROLE ;
              secret/data/dbt/github-actions SNOWFLAKE_DBT_USERNAME | SNOWFLAKE_DBT_USERNAME ;
              secret/data/dbt/github-actions SNOWFLAKE_DBT_WAREHOUSE | SNOWFLAKE_DBT_WAREHOUSE ;
              github/token/read_repositories token | GH_ORG_READ_REPO_TOKEN ;

      - name: Configure AWS Credentials
        if: ${{ inputs.aws_credentials_enabled }}
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ inputs.aws_github_role_name }}
          aws-region: eu-west-1

      - uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.python_version }}

      - name: Install Poetry
        uses: abatilo/actions-poetry@v4
        with:
          poetry-version: latest

      - name: Poetry install dependancies
        run: |
          poetry install --no-interaction --no-ansi --no-root

      - name: Upload manifest
        run: |
          poetry run dbt deps --project-dir ${{ env.DBT_PROFILES_DIR }}
          poetry run dbt compile --profile ${{ github.ref_name }} --project-dir ${{ env.DBT_PROFILES_DIR }}
          tar -czf ${{ env.DBT_PROFILES_DIR }}/target/valid_manifest.json.tar.gz -C ${{ env.DBT_PROFILES_DIR }}/target manifest.json
          aws s3 cp ${{ env.DBT_PROFILES_DIR }}/target/valid_manifest.json.tar.gz s3://${{ env.BACKUP_BUCKET_NAME }}/${{ github.event.repository.name }}/

      - name: Upload dbtdocs
        run: |
          poetry run dbt docs generate --profile ${{ github.ref_name }} --project-dir ${{ env.DBT_PROFILES_DIR }}
          aws s3 cp ${{ env.DBT_PROFILES_DIR }}/target/manifest.json s3://${{ env.TECH_PORTAL_DATA_BUCKET_NAME }}/dbtdocs/${{ github.event.repository.name }}/${{ github.ref_name }}/
          aws s3 cp ${{ env.DBT_PROFILES_DIR }}/target/catalog.json s3://${{ env.TECH_PORTAL_DATA_BUCKET_NAME }}/dbtdocs/${{ github.event.repository.name }}/${{ github.ref_name }}/
